### ISSUE TITLE
option to remove board name from web page

### ISSUE THREAD

**Issue by tomtobback** [khoih-prog/WiFiManager_NINA_Lite#25]
### Is your feature request related to a problem? Please describe.

The web page shows inputs for 2 sets of wifi credentials, and the board name. In my project, i have no use for the board name and would like to keep it as simple as possible. Is there a way to remove the board name from the web page?

### Describe the solution you'd like

It would be nice to have a `#define USE_BOARD_NAME false` that would enable to bypass the displaying of the field on the web page.

### Describe alternatives you've considered

I was tempted to change the HTML in the source code, but it shows a [warning](https://github.com/khoih-prog/WiFiManager_NINA_Lite/blob/b4aa1f2a6af21ad32b35b1a34b42ae8e9bb98634/src/WiFiManager_NINA_Lite_SAMD.h#L203) and i'd have to do that again whenever the library is updated.

**Comment by khoih-prog** [comment]
To remove board name from web page, just use

```
void begin(const char *iHostname = "")
```

with iHostname equal `space`, such as changing from

https://github.com/khoih-prog/WiFiManager_NINA_Lite/blob/b4aa1f2a6af21ad32b35b1a34b42ae8e9bb98634/examples/SAMD_WiFiNINA/SAMD_WiFiNINA.ino#L88

to

```
WiFiManager_NINA->begin(" ");
```

**Comment by tomtobback** [comment]
thanks i've tried it but i still see the Board Name input field in the web page form. i was thinking of an alternative solution, using `WiFiManager_NINA->setCustomsStyle(NewCustomsStyle)` to hide the element, but as far as i understand i can't do that because that `<div>` has no id so i can't select it in the style

**Comment by khoih-prog** [comment]
Hi @tomtobback 

Due to your vague description of your request, I was mistaken to think you'd like not to display the Board_Name on WebPage header. It turns out that you'd like not to use in `Config Portal Menu`.

Anyway, check the new [**WiFiManager_NINA_Lite releases v1.6.2**](https://github.com/khoih-prog/WiFiManager_NINA_Lite/releases/tag/v1.6.2) which has just been published.

Follow [**Not-using-Board_Name-on-Config_Portal**](https://github.com/khoih-prog/WiFiManager_NINA_Lite#14-Not-using-Board_Name-on-Config_Portal)

Best Regards,

---

### Release v1.6.2

1. Optimize code by passing by `reference` instead of `value`
2. Optional `Board_Name` in Config Portal. Check [option to remove board name from web page #25](https://github.com/khoih-prog/WiFiManager_NINA_Lite/issues/25)
3. Update `Packages' Patches`
---


![Selection_101](https://user-images.githubusercontent.com/57012152/154786114-3e11ce5c-b6e4-483e-85fe-9e0b19580a6c.png)
