### ISSUE TITLE
custom html header

### ISSUE THREAD

**Issue by piecol** [khoih-prog/WiFiManager_NINA_Lite#4]
hi,

would it be possible to add a parameter to define a custom html header ? this would provide a simple way to taylor the AP page to one's project in a safe way.

If not, what would be your recommended approach? currently, I hard-code it in the src/WiFiManager_NINA_Lite_SAMD.h file, but this might break with library upgrades.

```
String custom_html = "<!DOCTYPE html>..."

const char WIFININA_HTML_HEAD[]     /*PROGMEM*/ = custom_html;
```

thanks

**Comment by khoih-prog** [comment]
Hi @piecol 

Thanks for your interests in the library and the request for enhancement.

When I first started to write these Lite libraries, I just thought to make it simple, reliable and as much as useful as possible for many different types of boards / shields, with the trade-off being without customs and special case headers.

Now, with your first enhancement request, I'll add the capabilities of adding / modifying special customs headers, such as CORS, etc. as follows

1. Permanent in HTML

```
const char WM_HTTP_CACHE_CONTROL[]   PROGMEM = "Cache-Control";
const char WM_HTTP_NO_STORE[]        PROGMEM = "no-cache, no-store, must-revalidate";
const char WM_HTTP_PRAGMA[]          PROGMEM = "Pragma";
const char WM_HTTP_NO_CACHE[]        PROGMEM = "no-cache";
const char WM_HTTP_EXPIRES[]         PROGMEM = "Expires";
```  

2. Optional in HTML

```
const char WM_HTTP_CORS[]            PROGMEM = "Access-Control-Allow-Origin";
const char WM_HTTP_CORS_ALLOW_ALL[]  PROGMEM = "*";
```  

3. Functions for CORS, customs headers

```
void setCORSHeader(const char* CORSHeaders);
const char* getCORSHeader();
void setCustomsHeader(const char* CORSHeaders);
const char* getCustomsHeader();
```

What else do you suggest ?

Please wait for new release within several days.

**Comment by piecol** [comment]
hi @khoih-prog,

thanks for considering my request!

for the application I am developing it would be helpful to implement: 
- a captive portal once the connection with the AP is set, to avoid browsing for 192.168.4.1
- easy/basic stilying of the html page (set page background and button colors, border-radius of input/button, and such) 

cheers

**Comment by khoih-prog** [comment]
Hi @piecol 

The new release to support Configurable **Customs HTML Headers** has been published on Arduino as well as in PIO : [**WiFiManager_NINA_Lite**](https://platformio.org/lib/show/11836/WiFiManager_NINA_Lite).

Your contribution has been noted in [**Contributions and Thanks**](https://github.com/khoih-prog/WiFiManager_NINA_Lite#contributions-and-thanks)

Please have a look at

1. [**To use custom HTML Style**](https://github.com/khoih-prog/WiFiManager_NINA_Lite#8-to-use-custom-html-style)
2. [**To use custom Head Elements**](https://github.com/khoih-prog/WiFiManager_NINA_Lite#9-to-use-custom-head-elements)

The Captive Portal is not working reliably yet. You can try to include [WiFiManager_NINA_Lite_SAMD_CP.h](https://github.com/khoih-prog/WiFiManager_NINA_Lite/blob/master/src/WiFiManager_NINA_Lite_SAMD_CP.h) instead of  [WiFiManager_NINA_Lite_SAMD.h](https://github.com/khoih-prog/WiFiManager_NINA_Lite/blob/master/src/WiFiManager_NINA_Lite_SAMD.h) to see if Captive Portal is working for you.

---

#### Major Release v1.1.0

1. Configurable **Customs HTML Headers**, including Customs Style, Customs Gead Elements, CORS Header.
2. Add support to boards using WiFi101 library such as MKR1000
3. Fix Config Portal Bug. 
4. Add functions to control Config Portal from software or Virtual Switches. Check [How to trigger a Config Portal from code #25](https://github.com/khoih-prog/Blynk_WM/issues/25)
5. Use more efficient [FlashStorage_SAMD v1.1.0](https://github.com/khoih-prog/FlashStorage_SAMD) and [FlashStorage_STM32 v1.00](https://github.com/khoih-prog/FlashStorage_STM32)
6. Optimize code
7. Add Version String

**Comment by piecol** [comment]
Thanks @khoih-prog !

Great news :smiley:
