### ISSUE TITLE
Scan WiFi Network

### ISSUE THREAD

**Issue by LorenzoTecnab** [khoih-prog/WiFiManager_NINA_Lite#7]
Hi, first of all i thank you for the project. I like it and is very useful.
The only problem i can experienced is that often the SSID of a network is long and a useful enhancement may be to
scan for network and load in a combo from wich the user can choose the wifi to connect to.
How can i to accomplish at this task? Is very difficult to realize?
Thanks
Lorenzo

**Comment by bizprof** [comment]
Hi Lorenzo, great idea, and I certainly support this feature request. Some other WiFi Managers use a network scan that would then populate a drop-down. Only issue with that is a) SSIDs can be purposefully hidden from a scan, and b) an SSID you'd like to enter may be currently unavailable, or at a different location altogether. In both cases, they would not show up in the drop-down, so you still need to be able to input a custom value in addition to the drop-down.
Not sure how difficult this might be to realise. For the HTML to send to the CP, there is some suggested solution here, using a **datalist**: https://stackoverflow.com/questions/5650457/html-select-form-with-option-to-enter-custom-value. 
Hope this helps, and looking forward to Khoi's response!

**Comment by khoih-prog** [comment]
Hi All,

I'm very familiar with the WiFi scanning and auto-inputting. Have a look at my other **WiFiManager** libraries [**ESP_WiFiManager**](https://github.com/khoih-prog/ESP_WiFiManager) and [**ESPAsync_WiFiManager**](https://github.com/khoih-prog/ESPAsync_WiFiManager).

But as I said in [**Features**](https://github.com/khoih-prog/WiFiManager_NINA_Lite#features) and the library's name implying : WiFiManager_NINA_**Lite**, I try to make this as simplest as possible, without unnecessary baggage, so that it's easier to use anywhere, any board, any WiFi modules.

This library is designed for many boards, even the less powerful ones, and we can't expect **ESP32/ESP8266** kind of performance and power.

But I certainly will have a look at the "WiFi Scanning and auto-inputting" feature to see if it's OK to be included.

The timeline is undetermined as I'm have some more interesting and urgent works to do.

Thanks anyway,
